# Airplane Crashes Dataset Exercise

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../resources/airplane_crashes.csv")

## 1. Find the Number of rows and columns in the dataset

In [3]:
data.shape

(5268, 13)

## 2. Find the last 75 rows in the dataset

In [4]:
data.tail(75)

,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
5193,03/15/2008,08:15,"Nbagu, Nigeria",Trade Wings Aviation Ltd.,NaN,Lagos - Bebi Air Strip,Beechcraft 1900D,5N-JAH,UE-322,3.0,3.0,0.0,The plane crashed while en route. Wreckage was...
5194,04/03/2008,11:00,"Lawa, Suriname",Blue Wing Airlines,NaN,Paramaribo - Lawa,Antonov An-28,PZ-TSO,1AJ007-17,19.0,19.0,0.0,While attempting to land the crew aborted the ...
5195,04/09/2008,23:27,"Bundeena, Australia",Avtex Air Services,NaN,Sydney - Brisbane,Swearingen SA227AC Metroliner III,VH-OZA,AC-600,1.0,1.0,0.0,The pilot of the mail plane reported some mino...
5196,04/11/2008,22:15,"Chrisinau, Moldova",Kata Transportation,NaN,"Chrisinau, Moldova - Antalya, Turkey - Sudan",Antonov An-32,ST-AZL,3009,8.0,8.0,0.0,Just minutes after the take off the plane trie...
5197,04/15/2008,14:30,"Goma, Congo",Hewa Bora Airways,NaN,Goma - Kisangani - Kinshasa,McDonnell Douglas DC-9-51,9Q-CHN,47731,85.0,0.0,47.0,"While attempting to takeoff, the plane failed ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5263,05/20/2009,06:30,"Near Madiun, Indonesia",Military - Indonesian Air Force,NaN,Jakarta - Maduin,Lockheed C-130 Hercules,A-1325,1982,112.0,98.0,2.0,"While on approach, the military transport cras..."
5264,05/26/2009,NaN,"Near Isiro, DemocratiRepubliCongo",Service Air,NaN,Goma - Isiro,Antonov An-26,9Q-CSA,5005,4.0,4.0,NaN,The cargo plane crashed while on approach to I...
5265,06/01/2009,00:15,"AtlantiOcean, 570 miles northeast of Natal, Br...",Air France,447,Rio de Janeiro - Paris,Airbus A330-203,F-GZCP,660,228.0,228.0,0.0,The Airbus went missing over the AtlantiOcean ...
5266,06/07/2009,08:30,"Near Port Hope Simpson, Newfoundland, Canada",Strait Air,NaN,Lourdes de BlanSablon - Port Hope Simpson,Britten-Norman BN-2A-27 Islander,C-FJJR,424,1.0,1.0,0.0,The air ambulance crashed into hills while att...
5267,06/08/2009,NaN,"State of Arunachal Pradesh, India",Military - Indian Air Force,NaN,Mechuka for Jorhat,Antonov An-32,NaN,NaN,13.0,13.0,0.0,The military transport went missing while en r...

In [5]:
data.columns

Index(['Date', 'Time', 'Location', 'Operator', 'Flight #', 'Route', 'Type',
       'Registration', 'cn/In', 'Aboard', 'Fatalities', 'Ground', 'Summary'],
      dtype='str')

In [6]:
data.isna

<bound method DataFrame.isna of             Date   Time                                           Location  \
0     09/17/1908  17:18                                Fort Myer, Virginia
1     07/12/1912  06:30                            AtlantiCity, New Jersey
2     08/06/1913    NaN                 Victoria, British Columbia, Canada
3     09/09/1913  18:30                                 Over the North Sea
4     10/17/1913  10:30                         Near Johannisthal, Germany
...          ...    ...                                                ...
5263  05/20/2009  06:30                             Near Madiun, Indonesia
5264  05/26/2009    NaN                  Near Isiro, DemocratiRepubliCongo
5265  06/01/2009  00:15  AtlantiOcean, 570 miles northeast of Natal, Br...
5266  06/07/2009  08:30       Near Port Hope Simpson, Newfoundland, Canada
5267  06/08/2009    NaN                  State of Arunachal Pradesh, India

                             Operator Flight #  \
0                Military - U.S. Army      NaN
1                Military - U.S. Navy      NaN
2                             Private        -
3              Military - German Navy      NaN
4              Military - German Navy      NaN
...                               ...      ...
5263  Military - Indonesian Air Force      NaN
5264                      Service Air      NaN
5265                       Air France      447
5266                       Strait Air      NaN
5267      Military - Indian Air Force      NaN

                                          Route  \
0                                 Demonstration
1                                   Test flight
2                                           NaN
3                                           NaN
4                                           NaN
...                                         ...
5263                           Jakarta - Maduin
5264                               Goma - Isiro
5265                     Rio de Janeiro - Paris
5266  Lourdes de BlanSablon - Port Hope Simpson
5267                         Mechuka for Jorhat

                                  Type Registration cn/In  Aboard  Fatalities  \
0                     Wright Flyer III          NaN     1     2.0         1.0
1                            Dirigible          NaN   NaN     5.0         5.0
2                     Curtiss seaplane          NaN   NaN     1.0         1.0
3               Zeppelin L-1 (airship)          NaN   NaN    20.0        14.0
4               Zeppelin L-2 (airship)          NaN   NaN    30.0        30.0
...                                ...          ...   ...     ...         ...
5263           Lockheed C-130 Hercules       A-1325  1982   112.0        98.0
5264                     Antonov An-26       9Q-CSA  5005     4.0         4.0
5265                   Airbus A330-203       F-GZCP   660   228.0       228.0
5266  Britten-Norman BN-2A-27 Islander      C-FJJR    424     1.0         1.0
5267                     Antonov An-32          NaN   NaN    13.0        13.0

      Ground                                            Summary
0        0.0  During a demonstration flight, a U.S. Army fly...
1        0.0  First U.S. dirigible Akron exploded just offsh...
2        0.0  The first fatal airplane accident in Canada oc...
3        0.0  The airship flew into a thunderstorm and encou...
4        0.0  Hydrogen gas which was being vented was sucked...
...      ...                                                ...
5263     2.0  While on approach, the military transport cras...
5264     NaN  The cargo plane crashed while on approach to I...
5265     0.0  The Airbus went missing over the AtlantiOcean ...
5266     0.0  The air ambulance crashed into hills while att...
5267     0.0  The military transport went missing while en r...

[5268 rows x 13 columns]>

In [7]:
data.isna().sum()

Date               0
Time            2219
Location          20
Operator          18
Flight #        4199
Route           1707
Type              27
Registration     335
cn/In           1228
Aboard            22
Fatalities        12
Ground            22
Summary          390
dtype: int64

In [8]:
data.columns

Index(['Date', 'Time', 'Location', 'Operator', 'Flight #', 'Route', 'Type',
       'Registration', 'cn/In', 'Aboard', 'Fatalities', 'Ground', 'Summary'],
      dtype='str')

In [9]:
data['Fatalities'].describe()

count    5256.000000
mean       20.068303
std        33.199952
min         0.000000
25%         3.000000
50%         9.000000
75%        23.000000
max       583.000000
Name: Fatalities, dtype: float64

In [10]:
max_fatalities=data['Fatalities'].max()
result= data[data['Fatalities']==max_fatalities]
result['Date']

2963    03/27/1977
Name: Date, dtype: str

In [11]:
data['Aboard'].describe()

count    5246.000000
mean       27.554518
std        43.076711
min         0.000000
25%         5.000000
50%        13.000000
75%        30.000000
max       644.000000
Name: Aboard, dtype: float64

In [12]:
columns_to_study=['Aboard','Fatalities'] ## Number of passengers aboard vs fatalities per crash

In [13]:
data[columns_to_study]

      Aboard  Fatalities
0        2.0         1.0
1        5.0         5.0
2        1.0         1.0
3       20.0        14.0
4       30.0        30.0
...      ...         ...
5263   112.0        98.0
5264     4.0         4.0
5265   228.0       228.0
5266     1.0         1.0
5267    13.0        13.0

[5268 rows x 2 columns]

In [19]:
least_fatalities=data['Fatalities'].min()
least_fatalities_result=data[data['Fatalities']==0]
least_fatalities_result.columns

columnscleaned=[]
for i in least_fatalities_result.columns:
    columnscleaned.append(i.lower())

least_fatalities_result.columns=columnscleaned

In [20]:
least_fatalities_result.shape

(58, 13)

In [21]:
least_fatalities_result

,date,time,location,operator,flight #,route,type,registration,cn/in,aboard,fatalities,ground,summary
108,10/21/1926,13:15,English Channel,Imperial Airways,NaN,NaN,Handley Page W-10,G-EBMS,W10/3,12.0,0.0,0.0,The plane was on a flight from London to Paris...
387,03/05/1936,NaN,"Near Tengya, China",China National Aviation Corporation,NaN,NaN,Ford 5-AT-D Tri-Motor,NaN,NaN,6.0,0.0,0.0,Crash landed in mountains during a snowstorm.
889,10/08/1947,07:55,"Near El Paso, Texas",American Airlines,311,New York City - Dallas - Los Angeles,Douglas DC-4,NC90432,10314/DC45,54.0,0.0,0.0,"While cruising at 8,000 ft. in clear weather, ..."
897,11/11/1947,NaN,"Gallup, New Mexico",American Airlines,10,San Francisco - Chicago - New York,Douglas DC-6,NC90741,43046/92,25.0,0.0,0.0,The aircraft was on a flight from San Francisc...
1265,05/25/1953,15:30,"Amsterdam, Netherlands",KLM Royal Dutch Airlines,NaN,Amsterdam - Paris,Convair CV-240-4,PH-TEI,125,34.0,0.0,2.0,While taking off the plane reached a height of...
1359,01/19/1955,16:25,"Des Moines, Iowa",United Air Lines,329,Newark - Des Moines - Lincoln,Convair CV-340,N73154,180,39.0,0.0,0.0,Almost complete loss of elevator control and s...
1440,09/09/1956,NaN,"Bartlesville, Oklahoma",Continental Airlines,NaN,NaN,Douglas DC-3 / Cessna 170B,N33315 / N8143A,4978 / 20995,18.0,0.0,0.0,Midair collision. Both planes landed safely. F...
1443,10/16/1956,06:15,Over the PacifiOcean,Pan American World Airways,943,Honolulu - San Francisco,Boeing 377 Stratocruiser,N90943,15959,31.0,0.0,0.0,The aircraft ditched into the PacifiOcean whil...
1610,06/30/1959,10:35,"Ishikawa City, Ryukyu Island, Okinawa",Military - U.S. Air Force,NaN,NaN,North American F-100D-25NA,55-3633A,NaN,1.0,0.0,17.0,The pilot ejected and parachuted safely from t...
1837,02/28/1963,21:29,"Boston, Massachusetts",Eastern Air Lines,NaN,NaN,Douglas DC-7,N842D,454448/944,26.0,0.0,1.0,"With engines idling, a girl ran into the No. 2..."
1868,08/21/1963,12:15,"Near Leningrad , Russia",Aeroflot,NaN,Tallinn - Moscow,Tupelov Tu-124,CCCP-45021,2350701,52.0,0.0,0.0,After the landing gear did not retract after ...
1885,12/17/1963,23:41,"Los Angeles, California",Western Airlines,NaN,NaN,Douglas DC-6B,N93131,45536,46.0,0.0,0.0,The No 1. and No2. Engine propellers touched ...
1927,07/16/1964,18:29,"Richmond, Virginia",Eastern Air Lines,NaN,New York City - Richmond - Jacksonville,Douglas DC-7B,N809D,44860/616,76.0,0.0,0.0,"Landed 17 feet short of the runway threshold, ..."
1982,06/28/1965,13:10,"San Francisco, California",Pan American World Airways,NaN,San Francisco - Hawaii,Boeing B-707-321B,N761PA,18336,153.0,0.0,0.0,Just after the aircraft took off from San Fran...
1983,07/01/1965,05:29,"Kansas City, Missouri",Continental Airlines,12,"Los Angeles - Kansas City, MO",Boeing B-707-124,N70773,17609/25,66.0,0.0,0.0,The aircraft slid off the end of the runway wh...
2066,08/17/1966,NaN,"Near Da Nang, South Vietnam",Military - U.S. Marine Corps,NaN,NaN,Chance Vought F-8E,150321,NaN,1.0,0.0,33.0,"Following engine failure, the jet fighter cras..."
2247,08/28/1968,07:25,"Lopez, Washington",Island Sky Ferry - Air Taxi,NaN,NaN,Cessna 172,N2520Y,NaN,2.0,0.0,0.0,Misjudged altitude and crashed into water. Ri...
2266,11/22/1968,01:24,"San Francisco, California",Japan Air Lines,2,Tokyo - San Francisco,McDonnell Douglas DC-8-62,JA8032,45954,107.0,0.0,0.0,The plane landed in the shallow waters of San ...
2359,12/22/1969,10:30,"Near San Diego, California",Military U.S. Navy,NaN,NaN,LTVF-8J,150879,NaN,1.0,0.0,14.0,The fighter crashed into Miramar Naval Air Sta...
2486,07/30/1971,14:29,"San Francisco, California",Pan American World Airways,845,San Francisco - Los Angeles,Boeing B-747-121,N747PA,19639/2,218.0,0.0,0.0,The aircraft struck approach lights at the dep...
2590,09/24/1972,NaN,"Sacramento, California",Private,NaN,NaN,F-86 Sabrejet,N275X,NaN,1.0,0.0,22.0,A World War II vintage Sabrejet fighter leavin...
2835,08/07/1975,16:11,"Denver, Colorado",Continental Airlines,426,Denver - Wichita,Boeing B-727-224,N88777,19798/608,131.0,0.0,0.0,The aircraft climbed to about 100 feet above r...
3182,11/15/1979,12:00,"Near Chicago, Illinois",American Airlines,444,Chicago - Washington D.C.,Boeing B-727,NaN,NaN,78.0,0.0,0.0,While en route from Chicago to Washington an e...
3307,09/22/1981,12:00,"Near Babaeski, Turkey",Military - Turkish Air Force,NaN,NaN,Northrop F-5A,NaN,NaN,0.0,0.0,40.0,The fighter crashed into a village after the p...
3341,06/24/1982,20:44,"Mount Galunggung, Indonesia",British Airways,009,Kuala Lampur - Perth,Boeing B-747,G-BDXH,21635/365,257.0,0.0,0.0,The aircraft flew into a plume from a volcanie...
3366,07/23/1982,02:30,"Castaic, California",Western Helicopter,NaN,Movie set,Bell UH-1B Huey Helicopter,N87701,6414038,1.0,0.0,3.0,"During the filming of 'Twilight Zone, The Movi..."
3417,05/05/1983,09:15,"En route Miami, FL - Nassau, Bahamas",Eastern Air Lines,855,"Miami, FL - Nassau, Bahamas",Lockheed L-1011,N334EA,1141,172.0,0.0,0.0,Procedural error by maintenance crew caused O-...
3428,07/23/1983,19:30,"Gimli, Manitoba, Canada",Air Canada,143,Ottawa - Edmonton,Boeing B-767-233ER,C-GAUN,22520/47,69.0,0.0,0.0,The aircraft took off from Ottawa bound for Ed...
3470,02/28/1984,16:16,"JFK Airport, New York, New York",Scandinavian Airlines (SAS),901,"Oslo, Norway, New York, NY",McDonnell Douglas DC-10-30,LN-RKB,46871,177.0,0.0,0.0,"While attempting to land at JFK, New York, the..."
3541,02/19/1985,10:15,"300 nm NW of San Francisco, California",China Airlines (Taiwan),006,Taipei - Los Angeles,Boeing B-747-SP-09,N4522V,22805/564,274.0,0.0,0.0,The aircraft descended in an uncontrolable div...
3549,04/16/1985,11:37,"Las Cruces, New Mexico",American Airlines,NaN,"Dallas, TX - San Diego, CA",Boeing B-727-227,N718AA,20611/894,89.0,0.0,0.0,While cruising at FL 350 a loud noise was hear...
3611,03/27/1986,NaN,"Bangui, Central African Republic",Military - French Air Force,NaN,NaN,Sepecat Jaguar A,NaN,NaN,0.0,0.0,35.0,The jet fighter crashed into a school shortly ...
3767,05/24/1988,12:55,"New Orleans, Louisiana",TACA,NaN,"Belize City, Belize - New Orleans, LA",Boeing B-737-3T0,N75356,23838,45.0,0.0,0.0,The aircraft encountered heavy rain and hail w...
3927,03/01/1990,NaN,"Near Meerut, India",Military - Indian Air Force,NaN,NaN,MiG-23,NaN,NaN,1.0,0.0,50.0,"After the pilot ejected safely, the aircraft c..."
3950,06/10/1990,07:33,"Oxfordshire, England",British Airways,5390,"Birmingham, England - Malaga, Spain",BAC One-Eleven 528FL,G-BJRT,BAC 234,85.0,0.0,0.0,"While en route, at FL 173, a large section of ..."
4068,12/27/1991,08:51,"Stockholm, Sweden",Scandinavian Airlines (SAS),751,Stockholm-Copenhagen-Warsaw,MDonnell Douglas MD-81,OY-KHO,53003,129.0,0.0,0.0,"The aircraft reached an altitude of 3,000 feet..."
4117,07/30/1992,17:41,"JFK Airport, New York, New York",Trans World Airlines,843,New York City - San Francisco,Lockheed L-1011,N11002,1014,292.0,0.0,0.0,"Immediately after liftoff, the stick shaker ac..."
4171,03/31/1993,12:25,"Anchorage, Alaska",Japan Air Lines,46E,NaN,Boeing B-747-466,N47EV,26348,5.0,0.0,0.0,The No.2 engine and pylon separated from the a...
4199,08/18/1993,16:56,"Leeward Point Airfield, Guantanamo Bay, Cuba",American International Airways,808,"Norfolk, VA - Guantanamo, Cuba",McDonnell Douglas DC-8-61,N814CK,46127,3.0,0.0,0.0,The plane crashed 1/4 of a mile short of the r...
4231,03/02/1994,17:59,"New York, New York",Continental Airlines,795,New York City - Denver,McDonnell Douglas MD-82,N18835,49439,116.0,0.0,0.0,The aircraft overran the runway and came to re...
4242,03/23/1994,14:30,"Near Fayetteville, North Carolina",Military - U.S. Air Force / Military U.S. Air ...,NaN,NaN,GD F-16D / Lockheed C-130E,88-0171/6810942,1D-25 / 4322,7.0,0.0,23.0,The jet fighter collided in mid air with the t...
4273,08/10/1994,11:22,"Cheju, South Korea",Korean Airlines,2033,Seoul - Cheju,Airbus A300B4-622R,HL-7296,583,160.0,0.0,0.0,The aircraft overran the runway and caught fir...
4339,06/08/1995,19:08,"Atlanta, Georgia",ValuJet,597,Atlanta - Miami,McDonnell Douglas DC-9-32,N908VJ,47321,62.0,0.0,0.0,The right engine disintegrated and caught fire...
4543,02/03/1998,15:15,"Near Cavalese, Trento, Italy",Military - U.S. Marine Corps,-,NaN,Grummand EA-6B,163045/CY-02,P-130,2.0,0.0,20.0,The aircraft struck and severed the cable to a...
4553,03/22/1998,19:42,"Bacolod, Philippines",Philippine Air Lines,137,Manila - Bacolod,Airbus A.320-214,RP-C3222,708,127.0,0.0,3.0,"The aircraft overran the 6,888 ft. runway, wen..."
4594,10/21/1998,13:51,"Yerevan, Armenia",Ararat Avia,NaN,Yerevan - Krasnodar,Yakovlev YAK-40,EK-88272,9721053,37.0,0.0,4.0,"While attempting to take off, the aircraft str..."
4701,03/05/2000,18:11,"Burbank, Calilfornia",Southwest Airlines,1455,Las Vegas - Burbank,Boeing B-737-3T5,N668SW,23060/1069,142.0,0.0,0.0,"While attempting to land at Burbank Airport, t..."
4748,10/06/2000,16:55,"Reynosa, Mexico",Aeromexico,250,Mexico City - Reynosa - Matamoros,McDonnell Douglas DC-9-31,N936ML,47501/571,88.0,0.0,4.0,"The aircraft overshot the runway near Reynosa,..."
4797,08/24/2001,18:46,"Terceira, Azores",Canadian Air Transat,236,Toronto - Lisbon,Airbus A-330-243,C-GITS,0271,304.0,0.0,0.0,The crew reported that they had a loss of fuel...
4875,07/27/2002,12:45,"Lviv, Ukraine",Military - Ukraine Air Force,NaN,NaN,Sukhoi Su-27,42,NaN,2.0,0.0,85.0,The Su-76 was performing aerobatics when it cr...
5057,08/02/2005,16:04,"Toronto, Canada",Air France,358,"Paris, France - Toronto Canada",Airbus A-340,F-GLZQ,289,309.0,0.0,0.0,The plane landed almost half-way down Runway 2...
5074,12/08/2005,19:15,"Chicago, Illinois",Southwest Airlines,1248,"Baltimore, Maryland - Chicago, Illinois - Las ...",Boeing B-737-7H4,N471WN,32471/1535,103.0,0.0,1.0,The jetliner slid off Runway 13C at Chicago's ...
5134,01/25/2007,11:15,"Pau, France",Regional Compagnie Aerienne Europeenne,7775,Pau - Paris,Fokker 100,F-GMPG,11362,54.0,0.0,1.0,The crew abandoned their takeoff after the los...
5178,11/08/2007,08:00,"Khartoum, Sudan",Juba Air Cargo,NaN,Khartoum - Juba,Antonov 12,ST-JUA,3341110,4.0,0.0,2.0,"While taking off, an engine on the cargo plane..."
5186,01/17/2008,12:43,"London, England",British Airways,NaN,"Bejing, China - London, England",Boeing 777-236ER,G-YMMM,30314/342,152.0,0.0,0.0,The aircraft was on approach for landing on Ru...
5197,04/15/2008,14:30,"Goma, Congo",Hewa Bora Airways,NaN,Goma - Kisangani - Kinshasa,McDonnell Douglas DC-9-51,9Q-CHN,47731,85.0,0.0,47.0,"While attempting to takeoff, the plane failed ..."
5217,07/07/2008,03:50,"Near Bogota, Colombia",Centurian Air Cargo,NaN,"Bogota, Colombia - Miami, FL",Boeing B-747-209BSF,N714CK,22446/519,8.0,0.0,3.0,The cargo plane carrying a load of flowers had...
5245,01/15/2009,15:06,"New York, New York",US Airways,1549,"New York, NY- Charlotte, NC",Airbus A320-214,N106US,1044,155.0,0.0,0.0,The plane was taking off from La Guardia Airpo...