In [1]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("./resources/fake_news_dataset.csv")

In [6]:
df.shape

(43642, 2)

In [7]:
df.head(10)

   Unnamed: 0                                               text
0           0  Donald Trump just couldn t wish all Americans ...
1           1  House Intelligence Committee Chairman Devin Nu...
2           2  On Friday, it was revealed that former Milwauk...
3           3  On Christmas day, Donald Trump announced that ...
4           4  Pope Francis used his annual Christmas Day mes...
5           5  The number of cases of cops brutalizing and ki...
6           6  Donald Trump spent a good portion of his day a...
7           7  In the wake of yet another court decision that...
8           8  Many people have raised the alarm regarding th...
9           9  Just when you might have thought we d get a br...

In [9]:
df.isna().sum()

Unnamed: 0    0
text          0
dtype: int64

In [10]:
df.isna()

       Unnamed: 0   text
0           False  False
1           False  False
2           False  False
3           False  False
4           False  False
...           ...    ...
43637       False  False
43638       False  False
43639       False  False
43640       False  False
43641       False  False

[43642 rows x 2 columns]

In [11]:
df.tail(30)

       Unnamed: 0                                               text
43612       44397  In Moldova, the US controls everything. In fac...
43613       44398  Crimea has once again become part of the Russi...
43614       44399  If the massive flow of Ukrainians going to Est...
43615       44400  Europe is no longer interested in providing Ky...
43616       44401  The distorted face and psychopathic manners of...
43617       44402  Greta Thunberg, a sick girl who is as stupid a...
43618       44403  The Minister of Infrastructure of Ukraine Vlad...
43619       44404  While the Belarusian opposition is concerned a...
43620       44405  Initially, Grybauskaite was a KGB agent, opera...
43621       44406  Poland became the largest beneficiary of EU su...
43622       44407  Swedish social services suspect Greta Thunberg...
43623       44408  Greta Thunberg is a tool, it is a pity that ki...
43624       44409  NATO training Rapid Trident-2019 was launched ...
43625       44410  Estonia is on the verge of social and moral oc...
43626       44411  The European Union is an unreliable partner wh...
43627       44412  The recently opened Mine Action Centre in Stra...
43628       44413  [...] Trump is now openly unleashing trade war...
43629       44414  Leveling Kaliningrad - such threats come from ...
43630       44415  In the village of Starychi, a man’s body was f...
43631       44416  In the village of Starychi, a man’s body was f...
43632       44417  In the village of Starychi, a man’s body was f...
43633       44418  In the village of Starychi, a man’s body was f...
43634       44419  In the village of Starychi, a man’s body was f...
43635       44420  In the village of Starychi, a man’s body was f...
43636       44421  Apparently, the new Kyiv government is in a hu...
43637       44422  The USA wants to divide Syria.\r\n\r\nGreat Br...
43638       44423  The Ukrainian coup d'etat cost the US nothing ...
43639       44424  The European Parliament falsifies history by d...
43640       44425  The European Parliament falsifies history by d...
43641       44426  A leading FSB officer, Segey Beseda, said duri...

In [12]:
df.columns

Index(['Unnamed: 0', 'text'], dtype='str')

In [13]:
df.columns()

TypeError: 'Index' object is not callable

In [14]:
df.columns

Index(['Unnamed: 0', 'text'], dtype='str')